// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uufbuatrnoprynesbirw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1ZmJ1YXRybm9wcnluZXNiaXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODA2NTQsImV4cCI6MjA2NzA1NjY1NH0.1My4PFcOcrYV6NPaRFfTEIo4bpnjZA1wx93Nh5CX3Sc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});